pr:
- master

queue:
  name: Hosted VS2017

steps:
- task: PowerShell@2
  displayName: 'Initialize Environment'
  inputs:
    targetType: ./
    filePath: bootstrap.ps1

- powershell: 'Invoke-Build -Configuration Production -Task Test'
  displayName: 'Invoke Pester Tests'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: 'TestResults-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/TestResults'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage'
  inputs:
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/TestResults/CodeCoverage-*.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/TestResults'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: PSTelegramAPI'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/PSTelegramAPI'
    ArtifactName: PSTelegramAPI

- powershell: 'Invoke-Build -Configuration Production -Task PublishModule'
  displayName: 'Publish PowerShell Module'